print("SPEED CALCULATOR")
print("------------------------")
print("")
print("This program calculates the average speed of a scooter")
print("")
distance = input("What was the distance in meters traveled by the scooter? ")
time = input("How many minutes did the scooter take to cover this distance? ")
average_speed = float(distance) / float(time)
print("")
print("The scooter reached a speed of {0:.2f} m/min".format(average_speed))
